apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport
  namespace: logging
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: http
      nodePort: 32000 # Wählen Sie einen Port zwischen 30000-32767
  selector:
    app: elasticsearch-master
