serviceAccount:
  create: false
  name: fluentd
  namespace: kube-system

rbac:
  create: false

daemonset:
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule

  env:
    - name: FLUENT_ELASTICSEARCH_HOST
      value: "elastic.timourproject.com"
    - name: FLUENT_ELASTICSEARCH_PORT
      value: "80"
    - name: FLUENT_ELASTICSEARCH_SCHEME
      value: "http"
    - name: FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT
      value: "false"
    - name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
      value: "k8s-infra"
    - name: FLUENT_ELASTICSEARCH_INCLUDE_TIMESTAMP
      value: "true"
    - name: FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT
      value: "16"
    - name: FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL
      value: "1s"
    - name: FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE
      value: "10M"
    - name: FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH
      value: "16"
    - name: FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL
      value: "30"
    - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
      value: "false"
    - name: FLUENT_ELASTICSEARCH_USER
      value: "elastic"
    - name: FLUENT_ELASTICSEARCH_PASSWORD
      value: "1qazXSW@3edc"
    - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
      value: '["/var/log/containers/fluentd-*"]'

  resources:
    limits:
      memory: "200Mi"
    requests:
      cpu: "100m"
      memory: "200Mi"

  volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true

  volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
