---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      initContainers:
        - name: init-sysctl
          image: busybox:1.35
          command:
            - /bin/sh
            - -c
            - |
              sysctl -w fs.inotify.max_user_watches=524288
              sysctl -w fs.inotify.max_user_instances=512
              sysctl -w fs.file-max=131072
          securityContext:
            privileged: true
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.11.1-debian-elasticsearch7-1.3
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elastic.timourproject.com"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "80"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            - name: FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT
              value: "false"
            - name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
              value: "k8s-infra-%{+YYYY.MM.dd}"
            - name: FLUENT_ELASTICSEARCH_INCLUDE_TIMESTAMP
              value: "true"
            - name: FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT
              value: "4"
            - name: FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL
              value: "5s"
            - name: FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE
              value: "8M"
            - name: FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH
              value: "32"
            - name: FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL
              value: "30"
            - name: FLUENT_ELASTICSEARCH_BUFFER_RETRY_FOREVER
              value: "false"
            - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
              value: "false"
            - name: FLUENT_ELASTICSEARCH_USER
              value: "elastic"
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              value: "1qazXSW@3edc"
            - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
              value: '["/var/log/containers/fluentd-*"]'
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
            requests:
              cpu: 250m
              memory: 250Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add:
                - SYS_RESOURCE
                - SYS_ADMIN
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
